---
title: "Dewey_imputation"
output: html_document
date: "2024-05-24"
editor_options:
  chunk_output_type: console
---
```{r}
library(dplyr)
library(readr)
library(doParallel)
library(doRNG)
library(dplyr)
library(tidyr)
library(missForest)
setwd("<your_path_here>")
```

#1. select complete data and introduce NAs
```{r}
library(doParallel)
library(doRNG)
library(dplyr)
library(tidyr)
library(missForest)
```

```{r}
combined_dataframe<- read.csv("<your_path_here>")

combined_dataframe<- combined_dataframe%>%
  mutate(AIRCONDITIONINGCODE_recode = case_when(
    AIRCONDITIONINGCODE == 1 ~ "Central",
    AIRCONDITIONINGCODE == 2 ~ "Evaporative Cooler",
    AIRCONDITIONINGCODE == 3 ~ "None",
    AIRCONDITIONINGCODE == 4 ~ "Central",
    AIRCONDITIONINGCODE == 5 ~ "Others",
    AIRCONDITIONINGCODE == 6 ~ "None",
    AIRCONDITIONINGCODE == 7 ~ "Others",
    AIRCONDITIONINGCODE == 8 ~ "Others",
    AIRCONDITIONINGCODE == 9 ~ "Others",
    AIRCONDITIONINGCODE == 10 ~ "None",
    AIRCONDITIONINGCODE== 11 ~ "None",
    AIRCONDITIONINGCODE == 12 ~ "Others",
    AIRCONDITIONINGCODE == 13 ~ "Yes",
    AIRCONDITIONINGCODE == 14 ~ "Central",
    TRUE ~ as.character(AIRCONDITIONINGCODE) # for any other unexpected values
  ))




```

#numerical variables
```{r}
dfsel <- combined_dataframe %>%
    select(  AIRCONDITIONINGCODE, CONDITION, RESOWNER, HEATTYPE,PROPCLASS, YEARBUILT,RENOYEAR, BUILDSTYLE, TOTROOMS, STNUM, NUMFLOORS ) #

dfsel$AIRCONDITIONINGCODE<- as.character( dfsel$AIRCONDITIONINGCODE)
dfsel$CONDITION<- as.character( dfsel$CONDITION)
dfsel$HEATTYPE<- as.character( dfsel$HEATTYPE)

char_cols <- sapply( dfsel, is.character)

dfsel[char_cols] <- lapply( dfsel[char_cols], as.factor)

dfsel<- as.data.frame(dfsel)
```

```{r}
X_true <- select(dfsel, -AIRCONDITIONINGCODE)

set.seed(1)
X_missing <- prodNA(X_true, 0.2)

registerDoParallel(cores = 2)

registerDoRNG(seed = 1)
missForest_v1 <- missForest(X_missing, parallelize = 'forests', verbose = T) # 7 iterations seems good
missForest_v1 <- missForest(X_missing,  verbose = T,  maxiter = 3) # 3 iterations seems good
missForest_v2 <- missForest(X_missing,  maxiter = 3) #parallelize = 'forests',
missForest_v2$OOBerror
missForest_v1$OOBerror

```

```{r}
registerDoParallel(cores = 2)

mtry_used <- c()
OOB_NRMSE <- c()
OOB_PFC <- c()


#tuning

mtry_used <- c()
OOB_NRMSE <- c()
OOB_PFC <- c()

i <- 1

for (loop_seed in 1:3) {
  for (mtry in 1:15) {
    print(paste0("seed = ", loop_seed, ", mtry = ", mtry))

    registerDoRNG(seed = loop_seed)
    missForest_v3 <- missForest(X_missing ,
                                parallelize = 'forests',
                                ntree = 10,
                                maxiter = 7,
                                mtry = mtry)

    OOB_NRMSE[i] <- missForest_v3$OOBerror[1]
    OOB_PFC[i] <- missForest_v3$OOBerror[2]
    mtry_used[i] <- mtry

    i <- i + 1
  }
}

mtry_df <- data.frame(mtry_used, OOB_NRMSE, OOB_PFC) %>%
  group_by(mtry_used) %>%
  summarize(`OOB NRMSE` = mean(OOB_NRMSE),
            `OOB PFC` = mean(OOB_PFC)) %>%
  gather("metric", "error", -mtry_used)

```

```{r}
library(ggplot2)
ggplot(mtry_df, aes(x =  mtry_used, y = error, col = factor(metric))) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(2, 20, 2)) +
  scale_color_manual(values = c("deepskyblue", "mediumseagreen")) +
  facet_wrap(~ metric, scales = "free_y") +
  theme(legend.position = "none",
        axis.title.y = element_blank()) +
  labs(x = "mtry")


ggsave("<your_path_here>",dpi = 300)
```

```{r}
registerDoParallel(cores = 2)
#trying out ntree numbers
missForest_v1 <- missForest(dfsel, parallelize = 'forests', verbose = T, maxiter = 7, mtry = 10, ntree = 10)
missForest_v2 <- missForest(dfsel, parallelize = 'forests', verbose = T, maxiter = 7, mtry = 10, ntree = 1000)
missForest_v1$OOBerror
missForest_v2$OOBerror
```

```{r}
DFsel.mis.imputed <- missForest(dfsel,parallelize = 'forests', verbose = T, maxiter = 7, mtry = 4, ntree = 100)$ximp
```

#Main imputation
```{r}

library(dplyr)
library(readr)
library(doParallel)
library(doRNG)
library(dplyr)
library(tidyr)
library(missForest)
library(data.table)
setwd("<your_path_here>")
```

```{r}
# Read the file using fread
df <- fread("./Dewey_selected_data.csv")
#nrow(df) 157685796
df <- df %>%
  distinct(COUNTY, STATE, PROPID, .keep_all = TRUE)

dfindex <- df%>% select(c(PROPID))
dfselcat <-df%>% select(c( Classification,HEATTYPE,CONDITION,RESOWNER))

```

#checking NA ratio
```{r}
dfsel <- dplyr::select(df, -c(LAT,LON, AIRCONDITIONINGCODE,STATE,COUNTY,address,ZIPCODE,CNSSTRACT, PROPUSE, PROPCLASS, CNSSBLGR,NUMFLOORS,BUILDSTYLE))
dfsel$RESOWNER[dfsel$RESOWNER == ""] <- NA

na_summary <- dfsel %>%
  summarise_all(~ mean(is.na(.))) %>%
  pivot_longer(everything(), names_to = "Column", values_to = "Proportion_NA")

na_summary
test <- dfsel%>%filter(is.na(RENOYEAR))
```

# category values imputation
```{r}
# Create a lookup table
lookup_table <- data.frame(
  original = 1:25,
  recategory = c("Other", "Central", "Central", "Central", "Other", "Other",
                 "Other", "HeatPump", "Central", "Central", "Other", "Other", "Other",
                 "None", "Other", "Central", "Other", "Other", "Other", "Central",
                 "None", "Other", "Central", NA, "Other")
)
```

```{r}
dfselcat <- dfselcat %>%
  mutate(RESOWNER = ifelse(RESOWNER == "Y", "Y", NA))
dfselcat <- dfselcat %>%
  mutate(CONDITION = ifelse(CONDITION %in% c("1", "2", "3", "4", "5", "6","7"), CONDITION, NA))
dfselcat <- dfselcat %>%
  mutate(Classification = ifelse(Classification == "", NA, Classification))
dfselcat$REHEATTYPE <- lookup_table$recategory[match(dfselcat$HEATTYPE, lookup_table$original)]

setDT(dfselcat)

# Convert CONDITION and HEATTYPE to character
dfselcat[, CONDITION := as.character(CONDITION)]
dfselcat[, RESOWNER := as.character(RESOWNER)]

dfselcat[, Classification := as.character(Classification)]
dfselcat[, REHEATTYPE := as.character(REHEATTYPE)]
unique(dfselcat$Classification)

# Identify character columns
char_cols <- names(dfselcat)[sapply(dfselcat, is.character)]

# Convert character columns to factors
dfselcat[, (char_cols) := lapply(.SD, as.factor), .SDcols = char_cols]

# Check the structure to verify the changes
dfselcat<- as.data.frame(dfselcat)%>%select(-c("HEATTYPE"))
str(dfselcat)
```

```{r}

registerDoParallel(cores = 4)
start.time <- Sys.time()
imputed_chunk <- missForest(data_chunk, parallelize = 'forests', verbose = T, maxiter =3, mtry = 10, ntree = 100)$ximp
end.time <- Sys.time()
print(round(end.time - start.time,2))

rbind(dfindex[start_row:end_row, , drop = FALSE],imputed_chunk)
imputed_chunk$PROPID <- dfindex[start_row:end_row, , drop = FALSE]

```

# Categorical variable
```{r}
rm(df)
start.time <- Sys.time()
# Function to handle imputation for a chunk of data
impute_chunk <- function(data_chunk) {
  result <- missForest(data_chunk, parallelize = 'forest', verbose = TRUE, maxiter =3, mtry = 10, ntree = 100)
  return(as.data.table(result$ximp))
}

# Define chunk size
chunk_size <- 1000000  # Adjust based on your system's capacity
num_chunks <- ceiling(nrow(dfselcat) / chunk_size)

# Register parallel backend
registerDoParallel(cores = 4)

# Process each chunk in parallel #num_chunks
imputed_chunks <- foreach(i = 53:num_chunks, .combine = rbind, .packages = c("data.table", "missForest")) %dopar% {
  start_row <- ((i - 1) * chunk_size) + 1
  end_row <- min(i * chunk_size, nrow(dfselcat))

  # Debugging print statements
  cat("Processing chunk:", i, "Start row:", start_row, "End row:", end_row, "\n")

  # Extract data chunk
  data_chunk <- dfselcat[start_row:end_row, , drop = FALSE]

  # Debugging print statement
  cat("Data chunk size:", nrow(data_chunk), "\n")

  # Impute missing data in the chunk
  imputed_chunk <- tryCatch(
    {
      impute_chunk(data_chunk)
    },
    error = function(e) {
      cat("Error in chunk", i, ":", e$message, "\n")
      return(data_chunk)  # Return original chunk if error occurs
    }
  )

  # Add PROPID column
  imputed_chunk[, PROPID := dfindex[start_row:end_row, ]]

  return(imputed_chunk)
}

end.time <- Sys.time()
print(round(end.time - start.time,2))
imputed_chunks_df <- as.data.frame(imputed_chunks)

head(imputed_chunks_df)
write.csv(imputed_chunks_df, './/Dewey_categoryvalues_imputed_v2.csv', row.names = FALSE)

```

# numerica values imputation
```{r}
dfselnum <-df%>% dplyr::select(c(YEARBUILT,RENOYEAR,  TOTROOMS ))

dfselnum$YEARBUILT[dfselnum$YEARBUILT < 1800] <- NA
dfselnum$RENOYEAR[dfselnum$RENOYEAR < 1800] <- NA

#testing
start.time <- Sys.time()
imputed_chunk <- missForest(data_chunk, parallelize = 'forest', verbose = T, maxiter =7, mtry = 10, ntree = 100)$ximp
end.time <- Sys.time()
print(round(end.time - start.time,2))


```

#modified
```{r}
library(foreach)
library(doParallel)
library(data.table)
library(missForest)
dfselnum <-df%>% dplyr::select(c(YEARBUILT,RENOYEAR,  TOTROOMS ))

dfselnum$YEARBUILT[dfselnum$YEARBUILT < 1800] <- NA
dfselnum$RENOYEAR[dfselnum$RENOYEAR < 1800] <- NA


rm(df)
# Function to handle imputation for a chunk of data
impute_chunk <- function(data_chunk) {
  result <- missForest(data_chunk, parallelize = 'forest', verbose = TRUE, maxiter = 7, mtry = 10, ntree = 100)
  return(as.data.table(result$ximp))
}

# Define chunk size
chunk_size <- 1000000  # Adjust based on your system's capacity
num_chunks <- ceiling(nrow(dfselnum) / chunk_size)

# Register parallel back end
registerDoParallel(cores = 3)

start.time <- Sys.time()
# Function to show progress
progress <- function(i) {
  cat("Processing chunk:", i, "of", num_chunks, "\n")
}

# Process each chunk in parallel
imputed_chunks <- foreach(i = 1:num_chunks, .combine = rbind, .packages = c("data.table", "missForest"),
                          .options.snow = list(progress = progress)) %dopar% {

  # Randomly select rows for the chunk
  selected_rows <- sample(1:nrow(dfselnum), chunk_size, replace = FALSE)

  # Extract data chunk
  data_chunk <- dfselnum[selected_rows, , drop = FALSE]

  # Impute missing data in the chunk
  imputed_chunk <- tryCatch(
    {
      impute_chunk(data_chunk)
    },
    error = function(e) {
      cat("Error in chunk", i, ":", e$message, "\n")
      return(data_chunk)  # Return original chunk if error occurs
    }
  )

  # Add PROPID column
  imputed_chunk[, PROPID := dfindex[selected_rows, ]]

  return(imputed_chunk)
}

imputed_chunks_df <- as.data.frame(imputed_chunks)

head(imputed_chunks_df)

end.time <- Sys.time()
print(round(end.time - start.time,2))

write.csv(imputed_chunks_df, './HistoricalAC/Data/Dewey_numervalues_imputed_2part.csv',row.names = FALSE)
imputed_chunks_df2 <- read.csv('./HistoricalAC/Data/Dewey_numervalues_imputed.csv')

```


